### ISSUE TITLE
Work Package wp-af.csv

### ISSUE THREAD

**Issue by neilernst** [bhermann/DoR#23] opened 2021-05-12 20:12 UTC

**Comment by asslisa** [comment] 2021-07-12 15:52
I would like to work on this please!

**Comment by asslisa** [comment] 2021-07-15 12:01
Results of Phase 1

[wp-af-results.csv.txt](https://github.com/bhermann/DoR/files/6822872/wp-af-results.csv.txt)

https://doi.org/10.1145/3377811.3380437 took 24:08
https://doi.org/10.1145/3377811.3380377 took 19:16
https://doi.org/10.1145/3377811.3380342 took 15:02
https://doi.org/10.1145/3377811.3380341 took 21:20
https://doi.org/10.1145/3377811.3380324 took 16:01
https://doi.org/10.1145/3377811.3380355 took 17:26
https://doi.org/10.1145/3377811.3380329 took 12:54
https://doi.org/10.1145/3377811.3380348 took 24:32
https://doi.org/10.1145/3377811.3381749 took 15:28
https://doi.org/10.1145/3377811.3380433 took 20:14

**Comment by asslisa** [comment] 2021-07-15 12:01
I completed this work package.

**Comment by aysetosun** [comment] 2021-07-15 18:51
I would like to work on this please!

**Comment by aysetosun** [comment] 2021-07-16 13:27
Results of Phase 2
[wp-af-results.csv.txt](https://github.com/bhermann/DoR/files/6830947/wp-af-results.csv.txt)

**Comment by aysetosun** [comment] 2021-07-16 13:27
I completed this work package.

**Comment by aysetosun** [comment] 2021-07-16 13:29
Results of Phase 2

wp-af-results.csv.txt

https://doi.org/10.1145/3377811.3380437 took 18:00
https://doi.org/10.1145/3377811.3380377 took 15:00
https://doi.org/10.1145/3377811.3380342 took 08:00
https://doi.org/10.1145/3377811.3380341 took 40:00
https://doi.org/10.1145/3377811.3380324 took 16:00
https://doi.org/10.1145/3377811.3380355 took 08:00
https://doi.org/10.1145/3377811.3380329 took 15:00
https://doi.org/10.1145/3377811.3380348 took 08:00
https://doi.org/10.1145/3377811.3381749 took 07:00
https://doi.org/10.1145/3377811.3380433 took 07:00

**Comment by bhermann** [comment] 2021-07-17 10:30
Hi @asslisa and @aysetosun . Your results files use 7 columns in the data lines, but the column descriptions defines 8 columns. It seems that the `reused_doi` and `alt_url` columns seem to be merged here. Could you look into separating the values between the two columns? DOIs go in the left, anything else (URLs, arxiv IDs,...) so in the right.

**Comment by aysetosun** [comment] 2021-07-17 17:49
Hi @bhermann thanks for the warning. As we are changing the formats from .csv to .csv.txt, we realized that the columns were somehow merged. Both Asli and I checked our files in detail. We also realized there was a confusion in one of the papers' doi's. We also fixed that. We hope the problem is resolved with the updated versions. I am attaching my coding..
[wp-af-results.csv.txt](https://github.com/bhermann/DoR/files/6835095/wp-af-results.csv.txt)

**Comment by bhermann** [comment] 2021-07-17 17:50
Great! Thank you! I'll check and include this tomorrow.

**Comment by asslisa** [comment] 2021-07-17 17:56
I fixed the issue @bhermann, could you please check?
[wp-af-results.csv.txt](https://github.com/bhermann/DoR/files/6835111/wp-af-results.csv.txt)

**Comment by bhermann** [comment] 2021-07-18 15:34
Looks great! I included the work package into the repository. The data will appear soon on the website.
I corrected 4 10.5555 DOIs here. 
Thank you for your work on this!

**Comment by yrahul3910** [comment] 2021-07-20 04:12
@aysetosun Could you please use the DOI URLs (instead of the DOI itself) from your next work package? I'll add in the code to handle DOIs for this, so you don't need to make changes here.

**Comment by yrahul3910** [comment] 2021-07-20 05:26
@asslisa I've modified your first comment so that the parser will ignore the links to the broken CSV (see the first line); please do not remove that line.

**Closed** 2022-03-02 09:54 UTC
Labels: 3. collect statistics, ICSE2020
